services:
  database-dev:
    image: postgres:latest
    container_name: school-api-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school-api
  database-prod:
    image: postgres:latest
    container_name: school-api-prod
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school-api